force-app/main/default/objects/Address_Enrichment_Requested__e/Address_Enrichment_Requested__e.object-meta.xml
<CustomObject>
    <label>Address Enrichment Requested</label>
    <pluralLabel>Address Enrichment Requesteds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Address_Enrichment_Requested__e/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tests/AddressEnrichEventTriggerDmlTest.cls
@IsTest
private class AddressEnrichEventTriggerDmlTest {

    @IsTest
    static void trigger_deveEnfileirarQueueable_quandoEventoPublicado() {
        Application.Service.setMock(IAddressService.class, new AddressServiceMock());

        Id accountId = fflib_IDGenerator.generate(Account.SObjectType);

        Test.startTest();
        EventBus.publish(
            new Address_Enrichment_Requested__e(
                Cep__c = '01001000',
                RecordId__c = String.valueOf(accountId)
            )
        );
        Test.stopTest();

        System.assert(true);
    }

    private class AddressServiceMock implements IAddressService {
        public void enrichAddress(String cep, Id recordId) {
        }

        public void enrichAddresses(List<AddressEnrichmentRequest> requests) {
        }
    }
}